package com.company.courseManager.courseevaluation.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Model class of courseEvaluation.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CourseEvaluation implements Serializable {

	/**
	 * 回复 填写1
	 */
	public static final int IS_REPLY = 1;
	/**
	 * 回复 填写0
	 */
	public static final int IS_EVALUATION = 0;

	public static final int IS_TEACHE = 1;
	public static final int IS_STUDENT = 0;

	public static final int IS_createrisowner = 1;
	public static final int NOT_createrisowner = 0;

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	/**
	 * 评价ID createTime+orderId orderId=systemtime-creatTime + 100
	 */
	private String evaluationId;

	/** 课程ID. */
	private String courseId;

	/** 评价时间. */
	private Date createTime;

	/** 评价人ID. */
	private String createrUserId;

	/** 评价人名字. */
	private String createrUserName;

	/** 评价人头像. */
	private String createrAvatar;

	/** 评价人级别. */
	private String createrLevel;

	/** 评价人职称. */
	private String createrRank;

	/** 评价人类型(教师/学员). */
	private int createrType;

	/** 是否是课程发布者. */
	private int createrIsOwner;

	/** 评论内容. */
	private String content;

	/**
	 * 评价等级
	 */
	private int starLevel=5;
	
	/** 评论还是回复. 0--pinglun */
	private int createrIsReply;

	/** 回复发言者的名字. */
	private String replyName;

	/** 回复帖子的ID. */
	private String replyParentId;

	private List<CourseEvaluation> childEvaluation;

	/**
	 * Constructor.
	 */
	public CourseEvaluation() {
	}

	public int getStarLevel() {
		return starLevel;
	}

	public void setStarLevel(int starLevel) {
		this.starLevel = starLevel;
	}
	public String getEvaluationId() {
		return evaluationId;
	}

	public void setEvaluationId(String evaluationId) {
		this.evaluationId = evaluationId;
	}

	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreaterUserId() {
		return createrUserId;
	}

	public void setCreaterUserId(String createrUserId) {
		this.createrUserId = createrUserId;
	}

	public String getCreaterUserName() {
		return createrUserName;
	}

	public void setCreaterUserName(String createrUserName) {
		this.createrUserName = createrUserName;
	}

	public String getCreaterAvatar() {
		return createrAvatar;
	}

	public void setCreaterAvatar(String createrAvatar) {
		this.createrAvatar = createrAvatar;
	}

	public String getCreaterLevel() {
		return createrLevel;
	}

	public void setCreaterLevel(String createrLevel) {
		this.createrLevel = createrLevel;
	}

	public String getCreaterRank() {
		return createrRank;
	}

	public void setCreaterRank(String createrRank) {
		this.createrRank = createrRank;
	}

	public int getCreaterType() {
		return createrType;
	}

	public void setCreaterType(int createrType) {
		this.createrType = createrType;
	}

	public int getCreaterIsOwner() {
		return createrIsOwner;
	}

	public void setCreaterIsOwner(int createrIsOwner) {
		this.createrIsOwner = createrIsOwner;
	}
	
	public boolean isCreterOwner()
	{
		return createrIsOwner==IS_createrisowner;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	

	public int getCreaterIsReply() {
		return createrIsReply;
	}

	public void setCreaterIsReply(int createrIsReply) {
		this.createrIsReply = createrIsReply;
	}
	public boolean isReply()
	{
		return createrIsReply==IS_REPLY;
	}

	public String getReplyName() {
		return replyName;
	}

	public void setReplyName(String replyName) {
		this.replyName = replyName;
	}

	

	public String getReplyParentId() {
		return replyParentId;
	}

	public void setReplyParentId(String replyParentId) {
		this.replyParentId = replyParentId;
	}

	public List<CourseEvaluation> getChildEvaluation() {
		return childEvaluation;
	}

	public void setChildEvaluation(List<CourseEvaluation> childEvaluation) {
		this.childEvaluation = childEvaluation;
	}

	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
