package com.company.coursestudent.domain;
import java.io.Serializable;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Model class of ClassBuyerOrder.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Classbuyerorder implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 课时ID，标识一个视频的唯一编号. */
	private String classId;

	/** 课程编号. */
	private String courseId;


	/** 课时标题. */
	private String classTitle;
	
	/** 实际成交价格. */
	private float realPrice;

	/** 发布的原价. */
	private float originalPrice;

	/** 视频播放id. */
	private String vodeoId;

	/** 视频播放地址. */
	private String voidurl;

	/** 教师名称. */
	private String teacherName;

	
	/**
	 * Constructor.
	 */
	public Classbuyerorder() {
	}

	public String getClassId() {
		return classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public String getClassTitle() {
		return classTitle;
	}

	public void setClassTitle(String classTitle) {
		this.classTitle = classTitle;
	}

	public float getRealPrice() {
		return realPrice;
	}

	public void setRealPrice(float realPrice) {
		this.realPrice = realPrice;
	}

	public float getOriginalPrice() {
		return originalPrice;
	}

	public void setOriginalPrice(float originalPrice) {
		this.originalPrice = originalPrice;
	}

	public String getVodeoId() {
		return vodeoId;
	}

	public void setVodeoId(String vodeoId) {
		this.vodeoId = vodeoId;
	}

	public String getVoidurl() {
		return voidurl;
	}

	public void setVoidurl(String voidurl) {
		this.voidurl = voidurl;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	
}
