package com.company.coursestudent.domain;
import java.io.Serializable;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Model class of courseBuyerOrder.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Coursebuyerorder implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户ID. */
	private String userId;

	/** 课程编号. */
	private String courseId;

	/** 教师名称. */
	private String teacherName;

	/** 课程标题. */
	private String title;

	/** 课程头像. */
	private String courseAvatar;

	/** 实际成交价格. */
	private float realPrice;

	/** 发布的原价. */
	private float originalPrice;

	/** 订单原始总价格. */
	private float totalOriginalPrice;

	/** 实际成交的总价格. */
	private float totalRealPrice;

	private String feeType="CNY";
	
	/**
	 * Constructor.
	 */
	public Coursebuyerorder() {
	}

	public String getUserId() {
		return userId;
	}

	
	
	public String getFeeType() {
		return feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCourseAvatar() {
		return courseAvatar;
	}

	public void setCourseAvatar(String courseAvatar) {
		this.courseAvatar = courseAvatar;
	}

	public float getRealPrice() {
		return realPrice;
	}

	public void setRealPrice(float realPrice) {
		this.realPrice = realPrice;
	}

	public float getOriginalPrice() {
		return originalPrice;
	}

	public void setOriginalPrice(float originalPrice) {
		this.originalPrice = originalPrice;
	}

	public float getTotalOriginalPrice() {
		return totalOriginalPrice;
	}

	public void setTotalOriginalPrice(float totalOriginalPrice) {
		this.totalOriginalPrice = totalOriginalPrice;
	}

	public float getTotalRealPrice() {
		return totalRealPrice;
	}

	public void setTotalRealPrice(float totalRealPrice) {
		this.totalRealPrice = totalRealPrice;
	}

	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
