package com.company.coursestudent.domain;
import java.io.Serializable;

/**
 * Model class of courseBuyerOrder.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Coursebuyerorder implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户ID. */
	private String userid;

	/** 课程编号. */
	private String courseid;

	/** 教师名称. */
	private String teachername;

	/** 课程标题. */
	private String title;

	/** 课程头像. */
	private String courseavatar;

	/** 实际成交价格. */
	private float realprice;

	/** 发布的原价. */
	private float originalprice;

	/** 订单原始总价格. */
	private float totaloriginalprice;

	/** 实际成交的总价格. */
	private float totalrealprice;

	/**
	 * Constructor.
	 */
	public Coursebuyerorder() {
	}

	/**
	 * Set the 用户ID.
	 * 
	 * @param userid
	 *            用户ID
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * Get the 用户ID.
	 * 
	 * @return 用户ID
	 */
	public String getUserid() {
		return this.userid;
	}

	/**
	 * Set the 课程编号.
	 * 
	 * @param courseid
	 *            课程编号
	 */
	public void setCourseid(String courseid) {
		this.courseid = courseid;
	}

	/**
	 * Get the 课程编号.
	 * 
	 * @return 课程编号
	 */
	public String getCourseid() {
		return this.courseid;
	}

	/**
	 * Set the 教师名称.
	 * 
	 * @param teachername
	 *            教师名称
	 */
	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	/**
	 * Get the 教师名称.
	 * 
	 * @return 教师名称
	 */
	public String getTeachername() {
		return this.teachername;
	}

	/**
	 * Set the 课程标题.
	 * 
	 * @param title
	 *            课程标题
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the 课程标题.
	 * 
	 * @return 课程标题
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the 课程头像.
	 * 
	 * @param courseavatar
	 *            课程头像
	 */
	public void setCourseavatar(String courseavatar) {
		this.courseavatar = courseavatar;
	}

	/**
	 * Get the 课程头像.
	 * 
	 * @return 课程头像
	 */
	public String getCourseavatar() {
		return this.courseavatar;
	}

	/**
	 * Set the 实际成交价格.
	 * 
	 * @param realprice
	 *            实际成交价格
	 */
	public void setRealprice(float realprice) {
		this.realprice = realprice;
	}

	/**
	 * Get the 实际成交价格.
	 * 
	 * @return 实际成交价格
	 */
	public float getRealprice() {
		return this.realprice;
	}

	/**
	 * Set the 发布的原价.
	 * 
	 * @param originalprice
	 *            发布的原价
	 */
	public void setOriginalprice(float originalprice) {
		this.originalprice = originalprice;
	}

	/**
	 * Get the 发布的原价.
	 * 
	 * @return 发布的原价
	 */
	public float getOriginalprice() {
		return this.originalprice;
	}

	/**
	 * Set the 订单原始总价格.
	 * 
	 * @param totaloriginalprice
	 *            订单原始总价格
	 */
	public void setTotaloriginalprice(float totaloriginalprice) {
		this.totaloriginalprice = totaloriginalprice;
	}

	/**
	 * Get the 订单原始总价格.
	 * 
	 * @return 订单原始总价格
	 */
	public float getTotaloriginalprice() {
		return this.totaloriginalprice;
	}

	/**
	 * Set the 实际成交的总价格.
	 * 
	 * @param totalrealprice
	 *            实际成交的总价格
	 */
	public void setTotalrealprice(float totalrealprice) {
		this.totalrealprice = totalrealprice;
	}

	/**
	 * Get the 实际成交的总价格.
	 * 
	 * @return 实际成交的总价格
	 */
	public float getTotalrealprice() {
		return this.totalrealprice;
	}


}
