spring:
  datasource:
    name: lottery_db_name
    url: jdbc:mysql://127.0.0.1:3306/security_common
    username: cmanager
    password: cmanager
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20

  redis:
    cluster:
      nodes:
      - 101.200.166.163:9000
      - 101.200.166.163:9001
      - 101.200.166.163:9002
      - 101.200.166.163:9003
      - 101.200.166.163:9004
      - 101.200.166.163:9005  
      
fdfs:
  soTimeout: 1501
  connectTimeout: 601 
  thumbImageSize:
    width: 150
    height: 150
  trackerList:
     - 39.107.15.75:22122
  pool:
    #从池中借出的对象的最大数目
    maxTotal: 153
    #获取连接时的最大等待毫秒数100
    maxWaitMillis: 102    
  thumbImageScale:
    thumb-scale-list:
    - _middle:1.0:0.55
    - _large:1.0:0.55
    thumb-size-list:
    - _150:150:150